### ISSUE TITLE
same feature with different ASV number

### ISSUE THREAD

**Issue by BirongZhang** [OxfordCMS/OCMS_Example_16SrRNA#1]
Hi，

Thanks for sharing this useful tutorial! Learned a lot!

I have a question about the **asv.counts table**.
For example, ASV609, ASV610, and ASV611 all have the same features at every level. But because the ASV numbers are different, I assume they will be treated as different features in the downstream analysis. Does this make sense?
<img width="785" alt="Screenshot 2023-01-24 at 15 50 01" src="https://user-images.githubusercontent.com/74430395/214341664-b845d083-347b-49ec-bb76-9f3b0d54f697.png">

Any replies would be highly appreciated! Thanks.

Regards,
Birong

**Comment by nickilott** [comment]
Hi Birong,

Glad you found this useful. You are correct that in a differential abundance analysis for example each ASV will be tested separately (if you don't aggregate in any way) so you could in theory have multiple ASVs with the same taxonomic classification as beeing differentially abundant. Mostly I would aggregate counts at the genus level for downstream analysis like differential expression testing although I don't think the tutorial reflects this :)

**Comment by BirongZhang** [comment]
Hi Nick,

Thanks for your efficient reply! Very clear! 

I totally agree with differential expression analysis. For diversity analysis, I think we should also do aggregation. 
But I couldn't see this kind of information in the phyloseq official tutorials. 

How do you think? Thanks.

Kind regards,
Birong

**Comment by nickilott** [comment]
Personally I usually do alpha diversity on ASV counts (although there are arguments to not do this as dada2 removes singletons) but beta diversity on relative abundance at genus-level

**Comment by BirongZhang** [comment]
So I can use the table below as input to do beta diversity instead of ASV counts.
<img width="741" alt="Screenshot 2023-01-24 at 17 09 45" src="https://user-images.githubusercontent.com/74430395/214360647-00ddb7ae-7d44-4250-846e-2817e4b38cbf.png">

**Comment by nickilott** [comment]
yes if that is relative abundance and you use for example bray-curtis distance it should be fine

**Comment by BirongZhang** [comment]
🥳 Got it! Many thanks for your kind help and time!

**Comment by BirongZhang** [comment]
Hi Nick,

I hope you are well! 

Sorry to bother you again. I am really confused now.

I want to look for those features that are different between disease and control group.

I have done DESeq2 analysis, but I don't know whether DESeq2 is suitable for 16S rRNA data.  Now I am going to use Wilcox-test to see if I can find some common features between DESeq2 and Wilcox test results. 

However, I don't know which data should be used for input data.
Should I use **Log2( absolute / colSums(absolute) * 1E6)** or ** absolute / colSums(absolute)*100 **?

Could you please help me to have a look? Many thanks.

Best regards,
Birong
